export default {
    TASK_LIST_LOADING: 'TASK/TASK_LIST_LOADING',
    TASK_LIST_SUCCESS: 'TASK/TASK_LIST_SUCCESS',
    TASK_LIST_FAILED: 'TASK/TASK_LIST_FAILED',
    ADD_TASK: 'TASK/ADD_TASK',
    EDIT_TASK: 'TASK/EDIT_TASK',
    TOGGLE_TASK_STATUS: 'TASK/TOGGLE_TASK_STATUS',
}